// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvA1V20tConp9wPtbOzK7xIq4Ntr5LIco',
    appId: '1:719102814146:web:a1ad21c8d4f0f34b39185b',
    messagingSenderId: '719102814146',
    projectId: 'servenow-9440f',
    authDomain: 'servenow-9440f.firebaseapp.com',
    storageBucket: 'servenow-9440f.firebasestorage.app',
    measurementId: 'G-9EPZGVKE7V',
  );
}
